name: "Release"
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    - name: Test Action
      uses: ./
      with: 
        SECRETS: |
          ^TEST$
        REPOSITORIES: |
          ^Laugslander/secrets-sync-action$
        DRY_RUN: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_NO_SCOPES }}
      env:
        TEST: ${{ secrets.TEST }}
